name: Enhancement Request
description: Create a report to help us enhance a particular feature
title: "enhancement: "
labels:
  - "type: enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: related-feature
    attributes:
      label: Please state which of feature you have in mind and describe what are its shortcomings?
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal
    attributes:
      label: How would you imagine the enhancement of the feature?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is there any more labels you wish to add?
      description: Please search labels and identify those related to your enhancement.
      options:
      - label: I have searched labels and added any
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered:"
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context:"
      description: Add any other context or screenshots about the enhancement request here.
    validations:
      required: false