name: Milestone Release

on:
  workflow_dispatch:
  on:
    milestone:
      types: closed


jobs:
  test-milestone-title:
    run: |
      echo "${{ github.event.milestone.title }}"
  call-ci-tools-milestone-release:
    uses: ynput/ci-tools/.github/workflows/generate_changelog.yml@main
    with:
      milestone: ${{ github.event.milestone.title }}
      repo-owner: ${{ github.event.repository.owner.login }}
      repo-name: ${{ github.event.repository.name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}