name: Milestone - create default

on:
  milestone:
    types: [closed, edited]

jobs:
  generate-next-patch:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Milestones'
        uses: "WyriHaximus/github-action-get-milestones@master"
        id: milestones
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - run: echo  "name=number::%s" $(printenv MILESTONES | jq --arg MILESTONE $(printenv MILESTONE) '.[]  | select(.title == $MILESTONE) | .number')
        id: querymilestone
        env:
          MILESTONES: ${{ steps.milestones.outputs.milestones }}
          MILESTONE: "next-patch"

      - name: 'Create Milestone'
        if: steps.querymilestone.outputs.number == ''
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@master"
        with:
          title: "next-patch"
      # - uses: actions/checkout@v1
      # - name: 'Create `next-patch` milestone'
      #   id: createmilestone
      #   uses: "WyriHaximus/github-action-create-milestone@v1"
      #   with:
      #     title: 'next-patch'
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"