name: Milestone - next-patch

on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - 'develop'

jobs:
  assign-milestone:
    runs-on: ubuntu-latest

    steps:
      - uses: zoispag/action-assign-milestone@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: 'next-patch'