name: Stable Release test

on:
  workflow_dispatch:

jobs:
  release_milestone_minor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog - minor
        id: github_release
        uses: okcredit/changelog-creator-action@v1.0.0
        with:
          milestone: "3.3.0"
          failOnError: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print change log
        run: echo "Generated changelog > ${{steps.github_release.outputs.changelog}}"