name: 🐞 Update Bug Report

on:
  workflow_dispatch:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [published]

jobs:
  update-bug-report:
    runs-on: ubuntu-latest
    name: Update bug report
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Update version
        uses: ShaMan123/gha-populate-form-version@v2.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          registry: github
          dropdown: _version
          order: asc
          limit_to: 25
          form: .github/ISSUE_TEMPLATE/bug_report.yml
          commit_message: 'chore(): update bug report / version'