name: 🐞 Update Bug Report

on:
  workflow_dispatch:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [published]

jobs:
  update-bug-report:
    runs-on: ubuntu-latest
    name: Update bug report
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Update version
        uses: ynput/gha-populate-form-version@adding_regex_replace_pattern
        with:
          github_token: ${{ secrets.YNPUT_BOT_TOKEN }}
          github_user: ${{ secrets.CI_USER }}
          github_email: ${{ secrets.CI_EMAIL }}
          registry: github
          dropdown: _version
          limit_to: 25
          form: .github/ISSUE_TEMPLATE/bug_report.yml
          commit_message: 'chore(): update bug report / version'
